### ISSUE TITLE
Formatting of Step parameters in log should be readable

### ISSUE THREAD

**Issue by jdavies-st** [spacetelescope/stpipe#137]
Currently when a step runs, it outputs a log of the step parameters, or if it's a pipeline, the pipeline and constituent step parameters.  But it is basically unreadable, as one can see for example for `jwst.pipeline.Detector1Pipeline`:

> {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'save_calibrated_ramp': False, 'steps': {'group_scale': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': ''}, 'dq_init': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': ''}, 'emicorr': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': True, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'save_intermediate_results': False, 'user_supplied_reffile': None, 'nints_to_phase': None, 'nbins': None, 'scale_reference': True}, 'saturation': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'n_pix_grow_sat': 1}, 
> ...
> 'jump': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'rejection_threshold': 4.0, 'three_group_rejection_threshold': 6.0, 'four_group_rejection_threshold': 5.0, 'maximum_cores': '1', 'flag_4_neighbors': True, 'max_jump_to_flag_neighbors': 1000.0, 'min_jump_to_flag_neighbors': 10.0, 'after_jump_flag_dn1': 0.0, 'after_jump_flag_time1': 0.0, 'after_jump_flag_dn2': 0.0, 'after_jump_flag_time2': 0.0, 'expand_large_events': False, 'min_sat_area': 1.0, 'min_jump_area': 5.0, 'expand_factor': 2.0, 'use_ellipses': False, 'sat_required_snowball': True, 'min_sat_radius_extend': 2.5, 'sat_expand': 2, 'edge_size': 25, 'find_showers': False, 'extend_snr_threshold': 1.2, 'extend_min_area': 90, 'extend_inner_radius': 1.0, 'extend_outer_radius': 2.6, 'extend_ellipse_expand_ratio': 1.1, 'time_masked_after_shower': 15.0, 'max_extended_radius': 200, 'minimum_groups': 3, 'minimum_sigclip_groups': 100, 'only_use_ints': True}, 'ramp_fit': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'int_name': '', 'save_opt': False, 'opt_name': '', 'suppress_one_group': True, 'maximum_cores': '1'}, 'gain_scale': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': ''}}}

It would be much better to have formatted output.  Here's 3 options:

1. Use `yaml.dump()`
```
pre_hooks: []
post_hooks: []
output_file: None
output_dir: None
output_ext: .fits
output_use_model: False
output_use_index: True
save_results: False
skip: False
suffix: None
search_output_file: True
input_dir: ''
save_calibrated_ramp: False
steps:
  group_scale:
    pre_hooks: []
    post_hooks: []
    output_file: None
    output_dir: None
    output_ext: .fits
    output_use_model: False
    output_use_index: True
    save_results: False
    skip: False
    suffix: None
    search_output_file: True
    input_dir: ''
  dq_init:
    pre_hooks: []
    post_hooks: []
    output_file: None
    output_dir: None
    output_ext: .fits
    output_use_model: False
    output_use_index: True
    save_results: False
    skip: False
    suffix: None
    search_output_file: True
    input_dir: ''
  emicorr:
    pre_hooks: []
    post_hooks: []
    output_file: None
    output_dir: None
    output_ext: .fits
    output_use_model: False
    output_use_index: True
    save_results: False
    skip: True
    suffix: None
    search_output_file: True
    input_dir: ''
    save_intermediate_results: False
    user_supplied_reffile: None
    nints_to_phase: None
    nbins: None
    scale_reference: True
  saturation:
    pre_hooks: []
    post_hooks: []
    output_file: None
    output_dir: None
    output_ext: .fits
    output_use_model: False
    output_use_index: True
    save_results: False
    skip: False
    suffix: None
    search_output_file: True
    input_dir: ''
    n_pix_grow_sat: 1
...
  jump:
    pre_hooks: []
    post_hooks: []
    output_file: None
    output_dir: None
    output_ext: .fits
    output_use_model: False
    output_use_index: True
    save_results: False
    skip: False
    suffix: None
    search_output_file: True
    input_dir: ''
    rejection_threshold: 4.0
    three_group_rejection_threshold: 6.0
    four_group_rejection_threshold: 5.0
    maximum_cores: '1'
    flag_4_neighbors: True
    max_jump_to_flag_neighbors: 1000.0
    min_jump_to_flag_neighbors: 10.0
    after_jump_flag_dn1: 0.0
    after_jump_flag_time1: 0.0
    after_jump_flag_dn2: 0.0
    after_jump_flag_time2: 0.0
    expand_large_events: False
    min_sat_area: 1.0
    min_jump_area: 5.0
    expand_factor: 2.0
    use_ellipses: False
    sat_required_snowball: True
    min_sat_radius_extend: 2.5
    sat_expand: 2
    edge_size: 25
    find_showers: False
    extend_snr_threshold: 1.2
    extend_min_area: 90
    extend_inner_radius: 1.0
    extend_outer_radius: 2.6
    extend_ellipse_expand_ratio: 1.1
    time_masked_after_shower: 15.0
    max_extended_radius: 200
    minimum_groups: 3
    minimum_sigclip_groups: 100
    only_use_ints: True
  ramp_fit:
    pre_hooks: []
    post_hooks: []
    output_file: None
    output_dir: None
    output_ext: .fits
    output_use_model: False
    output_use_index: True
    save_results: False
    skip: False
    suffix: None
    search_output_file: True
    input_dir: ''
    int_name: ''
    save_opt: False
    opt_name: ''
    suppress_one_group: True
    maximum_cores: '1'
  gain_scale:
    pre_hooks: []
    post_hooks: []
    output_file: None
    output_dir: None
    output_ext: .fits
    output_use_model: False
    output_use_index: True
    save_results: False
    skip: False
    suffix: None
    search_output_file: True
    input_dir: ''
```

2. Use `json.dumps`
```
{
  "pre_hooks": [],
  "post_hooks": [],
  "output_file": None,
  "output_dir": None,
  "output_ext": ".fits",
  "output_use_model": False,
  "output_use_index": True,
  "save_results": False,
  "skip": False,
  "suffix": None,
  "search_output_file": True,
  "input_dir": "",
  "save_calibrated_ramp": False,
  "steps": {
    "group_scale": {
      "pre_hooks": [],
      "post_hooks": [],
      "output_file": None,
      "output_dir": None,
      "output_ext": ".fits",
      "output_use_model": False,
      "output_use_index": True,
      "save_results": False,
      "skip": False,
      "suffix": None,
      "search_output_file": True,
      "input_dir": ""
    },
    "dq_init": {
      "pre_hooks": [],
      "post_hooks": [],
      "output_file": None,
      "output_dir": None,
      "output_ext": ".fits",
      "output_use_model": False,
      "output_use_index": True,
      "save_results": False,
      "skip": False,
      "suffix": None,
      "search_output_file": True,
      "input_dir": ""
    },
    "emicorr": {
      "pre_hooks": [],
      "post_hooks": [],
      "output_file": None,
      "output_dir": None,
      "output_ext": ".fits",
      "output_use_model": False,
      "output_use_index": True,
      "save_results": False,
      "skip": True,
      "suffix": None,
      "search_output_file": True,
      "input_dir": "",
      "save_intermediate_results": False,
      "user_supplied_reffile": None,
      "nints_to_phase": None,
      "nbins": None,
      "scale_reference": True
    },
    "saturation": {
      "pre_hooks": [],
      "post_hooks": [],
      "output_file": None,
      "output_dir": None,
      "output_ext": ".fits",
      "output_use_model": False,
      "output_use_index": True,
      "save_results": False,
      "skip": False,
      "suffix": None,
      "search_output_file": True,
      "input_dir": "",
      "n_pix_grow_sat": 1
    },
...
    "jump": {
      "pre_hooks": [],
      "post_hooks": [],
      "output_file": None,
      "output_dir": None,
      "output_ext": ".fits",
      "output_use_model": False,
      "output_use_index": True,
      "save_results": False,
      "skip": False,
      "suffix": None,
      "search_output_file": True,
      "input_dir": "",
      "rejection_threshold": 4.0,
      "three_group_rejection_threshold": 6.0,
      "four_group_rejection_threshold": 5.0,
      "maximum_cores": "1",
      "flag_4_neighbors": True,
      "max_jump_to_flag_neighbors": 1000.0,
      "min_jump_to_flag_neighbors": 10.0,
      "after_jump_flag_dn1": 0.0,
      "after_jump_flag_time1": 0.0,
      "after_jump_flag_dn2": 0.0,
      "after_jump_flag_time2": 0.0,
      "expand_large_events": False,
      "min_sat_area": 1.0,
      "min_jump_area": 5.0,
      "expand_factor": 2.0,
      "use_ellipses": False,
      "sat_required_snowball": True,
      "min_sat_radius_extend": 2.5,
      "sat_expand": 2,
      "edge_size": 25,
      "find_showers": False,
      "extend_snr_threshold": 1.2,
      "extend_min_area": 90,
      "extend_inner_radius": 1.0,
      "extend_outer_radius": 2.6,
      "extend_ellipse_expand_ratio": 1.1,
      "time_masked_after_shower": 15.0,
      "max_extended_radius": 200,
      "minimum_groups": 3,
      "minimum_sigclip_groups": 100,
      "only_use_ints": True
    },
    "ramp_fit": {
      "pre_hooks": [],
      "post_hooks": [],
      "output_file": None,
      "output_dir": None,
      "output_ext": ".fits",
      "output_use_model": False,
      "output_use_index": True,
      "save_results": False,
      "skip": False,
      "suffix": None,
      "search_output_file": True,
      "input_dir": "",
      "int_name": "",
      "save_opt": False,
      "opt_name": "",
      "suppress_one_group": True,
      "maximum_cores": "1"
    },
    "gain_scale": {
      "pre_hooks": [],
      "post_hooks": [],
      "output_file": None,
      "output_dir": None,
      "output_ext": ".fits",
      "output_use_model": False,
      "output_use_index": True,
      "save_results": False,
      "skip": False,
      "suffix": None,
      "search_output_file": True,
      "input_dir": ""
    }
  }
}
```

3. Use `pprint.pformat()`
```
{'pre_hooks': [],
'post_hooks': [],
'output_file': None,
'output_dir': None,
'output_ext': '.fits',
'output_use_model': False,
'output_use_index': True,
'save_results': False,
'skip': False,
'suffix': None,
'search_output_file': True,
'input_dir': '',
'save_calibrated_ramp': False,
'steps': {'group_scale': {'pre_hooks': [],
                        'post_hooks': [],
                        'output_file': None,
                        'output_dir': None,
                        'output_ext': '.fits',
                        'output_use_model': False,
                        'output_use_index': True,
                        'save_results': False,
                        'skip': False,
                        'suffix': None,
                        'search_output_file': True,
                        'input_dir': ''},
         'dq_init': {'pre_hooks': [],
                    'post_hooks': [],
                    'output_file': None,
                    'output_dir': None,
                    'output_ext': '.fits',
                    'output_use_model': False,
                    'output_use_index': True,
                    'save_results': False,
                    'skip': False,
                    'suffix': None,
                    'search_output_file': True,
                    'input_dir': ''},
         'emicorr': {'pre_hooks': [],
                    'post_hooks': [],
                    'output_file': None,
                    'output_dir': None,
                    'output_ext': '.fits',
                    'output_use_model': False,
                    'output_use_index': True,
                    'save_results': False,
                    'skip': True,
                    'suffix': None,
                    'search_output_file': True,
                    'input_dir': '',
                    'save_intermediate_results': False,
                    'user_supplied_reffile': None,
                    'nints_to_phase': None,
                    'nbins': None,
                    'scale_reference': True},
         'saturation': {'pre_hooks': [],
                       'post_hooks': [],
                       'output_file': None,
                       'output_dir': None,
                       'output_ext': '.fits',
                       'output_use_model': False,
                       'output_use_index': True,
                       'save_results': False,
                       'skip': False,
                       'suffix': None,
                       'search_output_file': True,
                       'input_dir': '',
                       'n_pix_grow_sat': 1},
...
         'jump': {'pre_hooks': [],
                 'post_hooks': [],
                 'output_file': None,
                 'output_dir': None,
                 'output_ext': '.fits',
                 'output_use_model': False,
                 'output_use_index': True,
                 'save_results': False,
                 'skip': False,
                 'suffix': None,
                 'search_output_file': True,
                 'input_dir': '',
                 'rejection_threshold': 4.0,
                 'three_group_rejection_threshold': 6.0,
                 'four_group_rejection_threshold': 5.0,
                 'maximum_cores': '1',
                 'flag_4_neighbors': True,
                 'max_jump_to_flag_neighbors': 1000.0,
                 'min_jump_to_flag_neighbors': 10.0,
                 'after_jump_flag_dn1': 0.0,
                 'after_jump_flag_time1': 0.0,
                 'after_jump_flag_dn2': 0.0,
                 'after_jump_flag_time2': 0.0,
                 'expand_large_events': False,
                 'min_sat_area': 1.0,
                 'min_jump_area': 5.0,
                 'expand_factor': 2.0,
                 'use_ellipses': False,
                 'sat_required_snowball': True,
                 'min_sat_radius_extend': 2.5,
                 'sat_expand': 2,
                 'edge_size': 25,
                 'find_showers': False,
                 'extend_snr_threshold': 1.2,
                 'extend_min_area': 90,
                 'extend_inner_radius': 1.0,
                 'extend_outer_radius': 2.6,
                 'extend_ellipse_expand_ratio': 1.1,
                 'time_masked_after_shower': 15.0,
                 'max_extended_radius': 200,
                 'minimum_groups': 3,
                 'minimum_sigclip_groups': 100,
                 'only_use_ints': True},
         'ramp_fit': {'pre_hooks': [],
                     'post_hooks': [],
                     'output_file': None,
                     'output_dir': None,
                     'output_ext': '.fits',
                     'output_use_model': False,
                     'output_use_index': True,
                     'save_results': False,
                     'skip': False,
                     'suffix': None,
                     'search_output_file': True,
                     'input_dir': '',
                     'int_name': '',
                     'save_opt': False,
                     'opt_name': '',
                     'suppress_one_group': True,
                     'maximum_cores': '1'},
         'gain_scale': {'pre_hooks': [],
                       'post_hooks': [],
                       'output_file': None,
                       'output_dir': None,
                       'output_ext': '.fits',
                       'output_use_model': False,
                       'output_use_index': True,
                       'save_results': False,
                       'skip': False,
                       'suffix': None,
                       'search_output_file': True,
                       'input_dir': ''}}}
```

@hbushouse and @nden, 👍 or 👎?  And if so, which of the 3 is preferable?
