### ISSUE TITLE
Use tmp_path instead of tmpdir pytest fixture

### ISSUE THREAD

**Issue by jdavies-st** [spacetelescope/stpipe#145]
Replace all instances thereof, and then in pyproject.toml:

```toml
[tool.pytest.ini_options]
addopts = [
    "-p no:legacypath",
]
```

This is will make the code more robust for use of `pathlib.Path` instances in the runtime code.
