### ISSUE TITLE
Move strun to project.scripts in pyproject.toml

### ISSUE THREAD

**Issue by jdavies-st** [spacetelescope/stpipe#99]
Currently, `strun` lives on it's own in scripts and is pulled in via shenanigans via setup.py.  It should really have it's own entry in pyproject.toml:

```toml
[project.scripts]
stpipe = 'stpipe.cli.main:main'
```

and live with the rest of the cli scripts.
